become_override: false
ocp_username: opentlc-mgr
silent: false
guid: test

# ------------------------------------------------
# OpenShift Gitops
# ------------------------------------------------

ocp4_workload_connectivity_link_openshift_gitops_operator_channel: latest
ocp4_workload_connectivity_link_openshift_gitops_operator_automatic_install_plan_approval: true
ocp4_workload_connectivity_link_openshift_gitops_operator_starting_csv: ""
ocp4_workload_connectivity_link_openshift_gitops_operator_name: openshift-gitops-operator
ocp4_workload_connectivity_link_openshift_gitops_operator_namespace: openshift-operators
ocp4_workload_connectivity_link_openshift_gitops_operator_catalog: redhat-operators
ocp4_workload_connectivity_link_openshift_gitops_operator_use_catalog_snapshot: false
ocp4_workload_connectivity_link_openshift_gitops_operator_catalogsource_name: ""
ocp4_workload_connectivity_link_openshift_gitops_operator_catalogsource_namespace: openshift-operators
ocp4_workload_connectivity_link_openshift_gitops_operator_catalog_snapshot_image: ""
ocp4_workload_connectivity_link_openshift_gitops_operator_catalog_snapshot_image_tag: ""

ocp4_workload_connectivity_link_openshift_gitops_setup_cluster_admin: true

ocp4_workload_connectivity_link_openshift_gitops_update_route_tls: true

ocp4_workload_connectivity_link_openshift_gitops_update_resources: true

# ApplicationSet Controller
ocp4_workload_connectivity_link_openshift_gitops_applicationset_controller_update: false
ocp4_workload_connectivity_link_openshift_gitops_applicationset_controller_requests_cpu: 250m
ocp4_workload_connectivity_link_openshift_gitops_applicationset_controller_requests_memory: 512Mi
ocp4_workload_connectivity_link_openshift_gitops_applicationset_controller_limits_cpu: "2"
ocp4_workload_connectivity_link_openshift_gitops_applicationset_controller_limits_memory: 1Gi

# Application Controller
ocp4_workload_connectivity_link_openshift_gitops_controller_update: false
ocp4_workload_connectivity_link_openshift_gitops_controller_requests_cpu: 512m
ocp4_workload_connectivity_link_openshift_gitops_controller_requests_memory: 1Gi
ocp4_workload_connectivity_link_openshift_gitops_controller_limits_cpu: "4"
ocp4_workload_connectivity_link_openshift_gitops_controller_limits_memory: 4Gi
# Setting a default value for reconcile timeout as it needs to be configurable
# Reduce this value if you want to sync more frequently
ocp4_workload_connectivity_link_openshift_gitops_controller_app_sync: 3m

ocp4_workload_connectivity_link_openshift_gitops_controller_remove_memory_limits: false

# Redis
ocp4_workload_connectivity_link_openshift_gitops_redis_update: false
ocp4_workload_connectivity_link_openshift_gitops_redis_requests_cpu: 250m
ocp4_workload_connectivity_link_openshift_gitops_redis_requests_memory: 128Mi
ocp4_workload_connectivity_link_openshift_gitops_redis_limits_cpu: 500m
ocp4_workload_connectivity_link_openshift_gitops_redis_limits_memory: 256Mi

# Repo Server
ocp4_workload_connectivity_link_openshift_gitops_repo_update: false
ocp4_workload_connectivity_link_openshift_gitops_repo_requests_cpu: 500m
ocp4_workload_connectivity_link_openshift_gitops_repo_requests_memory: 512Mi
ocp4_workload_connectivity_link_openshift_gitops_repo_limits_cpu: "2"
ocp4_workload_connectivity_link_openshift_gitops_repo_limits_memory: 2Gi

# DEX
ocp4_workload_connectivity_link_openshift_gitops_dex_update: false
ocp4_workload_connectivity_link_openshift_gitops_dex_requests_cpu: 125m
ocp4_workload_connectivity_link_openshift_gitops_dex_requests_memory: 128Mi
ocp4_workload_connectivity_link_openshift_gitops_dex_limits_cpu: 500m
ocp4_workload_connectivity_link_openshift_gitops_dex_limits_memory: 256Mi

# Server
ocp4_workload_connectivity_link_openshift_gitops_server_update: false
ocp4_workload_connectivity_link_openshift_gitops_server_requests_cpu: 250m
ocp4_workload_connectivity_link_openshift_gitops_server_requests_memory: 128Mi
ocp4_workload_connectivity_link_openshift_gitops_server_limits_cpu: 500m
ocp4_workload_connectivity_link_openshift_gitops_server_limits_memory: 256Mi

ocp4_workload_connectivity_link_openshift_gitops_resource_customizations: |
  operators.coreos.com/Subscription:
    health.lua: |
      health_status = {}
      if obj.status ~= nil then
        if obj.status.conditions ~= nil then
          numDegraded = 0
          numPending = 0
          msg = ""
          for i, condition in pairs(obj.status.conditions) do
            msg = msg .. i .. ": " .. condition.type .. " | " .. condition.status .. "\n"
            if condition.type == "InstallPlanPending" and condition.status == "True" then
              numPending = numPending + 1
            elseif (condition.type == "InstallPlanMissing" and condition.reason ~= "ReferencedInstallPlanNotFound") then
              numDegraded = numDegraded + 1
            elseif (condition.type == "CatalogSourcesUnhealthy" or condition.type == "InstallPlanFailed") and condition.status == "True" then
              numDegraded = numDegraded + 1
            end
          end
          if numDegraded == 0 and numPending == 0 then
            health_status.status = "Healthy"
            health_status.message = msg
            return health_status
          elseif numPending > 0 and numDegraded == 0 then
            health_status.status = "Progressing"
            health_status.message = "An install plan for a subscription is pending installation"
            return health_status
          else
            health_status.status = "Degraded"
            health_status.message = msg
            return health_status
          end
        end
      end
      health_status.status = "Progressing"
      health_status.message = "An install plan for a subscription is pending installation"
      return health_status

  monitoring.coreos.com/Prometheus:
    health.lua: |
      local hs={ status = "Progressing", message = "Waiting for initialization" }
      found_status = false

      if obj.status ~= nil then
        found_status = true
        if obj.status.conditions ~= nil then
          for i, condition in ipairs(obj.status.conditions) do

            if condition.type == "Available" and condition.status ~= "True" then
              if condition.reason == "SomePodsNotReady" then
                hs.status = "Progressing"
              else
                hs.status = "Degraded"
              end
              hs.message = condition.message or condition.reason
            end
            if condition.type == "Available" and condition.status == "True" then
              hs.status = "Healthy"
              hs.message = "All instances are available"
            end
          end
        end
      end

      if not found_status then
          hs = { status = "Healthy", message = "All instances are available" }
      end

      return hs
