---

- name: Install Kuadrant operator
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'kuadrant_operator_applicationset.yaml.j2') | from_yaml }}"

- name: Install Kuadrant
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'kuadrant_applicationset.yaml.j2') | from_yaml }}"
