---

- name: Create ArgoCD manager service account
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'argocd_manager_service_account.yaml.j2') | from_yaml }}"

- name: Create ArgoCD token secret
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'argocd_manager_token_secret.yaml.j2') | from_yaml }}"

- name: Create ArgoCD manager clusterrole
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'argocd_manager_clusterrole.yaml.j2') | from_yaml }}"

- name: Create ArgoCD manager clusterrole binding
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'argocd_manager_clusterrole_binding.yaml.j2') | from_yaml }}"

- name: Get ArgoCD token secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: secret
    namespace: "kube-system"
    name: "{{ ocp4_workload_connectivity_link_argocd_manager_service_account }}-token"
  register: r_argocd_manager_token_secret

- name: Get the data from the token secret
  ansible.builtin.set_fact:
    r_argocd_manager_token: "{{ r_argocd_manager_token_secret.resources[0].data.token | b64decode }}"
    r_argocd_manager_certificate: "{{ r_argocd_manager_token_secret | json_query('resources[0].data.\"ca.crt\"') }}"

- name: Add local cluster to ArgoCD
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'argocd_cluster_secret.yaml.j2') | from_yaml }}"

- name: Add repository to ArgoCD
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'argocd_repo_secret.yaml.j2') | from_yaml }}"

- name: Add infra app project
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'argocd_infra_project.yaml.j2') | from_yaml }}"
